import { createContext, useContext, useState, useCallback, ReactNode, useEffect } from "react";

export type Language = "en" | "ta" | "hi" | "ml" | "te" | "kn" | "mr" | "bn";

export const LANGUAGES: { code: Language; label: string; nativeLabel: string }[] = [
  { code: "en", label: "English", nativeLabel: "English" },
  { code: "ta", label: "Tamil", nativeLabel: "தமிழ்" },
  { code: "hi", label: "Hindi", nativeLabel: "हिन्दी" },
  { code: "ml", label: "Malayalam", nativeLabel: "മലയാളം" },
  { code: "te", label: "Telugu", nativeLabel: "తెలుగు" },
  { code: "kn", label: "Kannada", nativeLabel: "ಕನ್ನಡ" },
  { code: "mr", label: "Marathi", nativeLabel: "मराठी" },
  { code: "bn", label: "Bengali", nativeLabel: "বাংলা" },
];

// Translation dictionaries
const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navbar
    "nav.home": "Home",
    "nav.dashboard": "Dashboard",
    "nav.schemes": "Schemes",
    "nav.analytics": "Analytics",
    "nav.reportIssue": "Report Issue",
    // Landing
    "landing.badge": "India's Public Fund Transparency Platform",
    "landing.title1": "India",
    "landing.title2": "Fund & Scheme",
    "landing.title3": "Tracker",
    "landing.subtitle": "Real-time visibility into how government welfare schemes are allocated, spent, and verified across India.",
    "landing.exploreDashboard": "Explore Dashboard",
    "landing.viewAllSchemes": "View All Schemes",
    "landing.howItWorks": "How Transparency Works",
    "landing.howItWorksDesc": "Every feature designed to ensure public accountability across India.",
    "landing.activeSchemes": "Active Schemes",
    "landing.govProgrammes": "Government welfare programmes across India",
    "landing.schemesIn": "Schemes in",
    "landing.viewAll": "View all",
    // Features
    "feature.realTimeTracking": "Real-Time Tracking",
    "feature.realTimeTrackingDesc": "Monitor every rupee from allocation to expenditure with live updates across all states.",
    "feature.proofVerification": "Proof Verification",
    "feature.proofVerificationDesc": "Every expense backed by invoices, photos, and geo-location data.",
    "feature.dataAnalytics": "Data Analytics",
    "feature.dataAnalyticsDesc": "Interactive charts showing spending patterns across departments and states.",
    "feature.aiFraudDetection": "AI Fraud Detection",
    "feature.aiFraudDetectionDesc": "Machine learning flags unusual spending patterns automatically.",
    "feature.panIndiaCoverage": "Pan-India Coverage",
    "feature.panIndiaCoverageDesc": "Track schemes across all 28 states, 8 UTs, and Central Government.",
    "feature.transparencyScore": "Transparency Score",
    "feature.transparencyScoreDesc": "Every project gets a public accountability score.",
    // Stats
    "stat.totalBudget": "Total Budget",
    "stat.totalSpent": "Total Spent",
    "stat.utilized": "utilized",
    "stat.activeSchemes": "Active Schemes",
    "stat.statesCovered": "States Covered",
    "stat.statesUTs": "States & UTs",
    "stat.avgUtilization": "Avg. Utilization",
    "stat.totalSchemes": "Total Schemes",
    "stat.departments": "Departments",
    "stat.districts": "Districts",
    "stat.verifiedExpenses": "Verified Expenses",
    "stat.flaggedItems": "Flagged Items",
    "stat.needsReview": "Needs review",
    "stat.fromDatabase": "from database",
    // Dashboard
    "dashboard.title": "Citizen Dashboard",
    "dashboard.subtitle": "Real-time overview of public fund utilization",
    "dashboard.stateAllocation": "State-wise Allocation",
    "dashboard.topDistricts": "Top Districts by Allocation",
    "dashboard.budgetVsSpent": "Budget vs Spent (₹ Crore)",
    "dashboard.byCategory": "By Category",
    "dashboard.fundDistribution": "Fund distribution",
    "dashboard.deptSpending": "Department-wise Spending",
    "dashboard.allActiveSchemes": "All Active Schemes",
    // Schemes page
    "schemes.allIndia": "All India Government Schemes",
    "schemes.stateSchemes": "Schemes",
    "schemes.browseDesc": "Browse and track public welfare programmes • Use the state selector in the navbar to filter by state",
    "schemes.search": "Search schemes, states, departments...",
    "schemes.allTypes": "All Types",
    "schemes.centralGovt": "Central Govt",
    "schemes.stateGovt": "State Govt",
    "schemes.loading": "Loading schemes...",
    "schemes.noResults": "No schemes found matching your criteria.",
    // Scheme detail
    "detail.allSchemes": "All Schemes",
    "detail.notFound": "Scheme not found",
    "detail.backToSchemes": "Back to Schemes",
    "detail.spent": "Spent",
    "detail.budget": "Budget",
    "detail.remaining": "Remaining",
    "detail.districtAllocation": "District-wise Allocation",
    "detail.recentExpenses": "Recent Expenses",
    "detail.noExpenses": "No expenses recorded yet.",
    "detail.districtBreakdown": "District Breakdown",
    "detail.district": "District",
    "detail.allocated": "Allocated",
    "detail.utilization": "Utilization",
    "detail.progress": "Progress",
    // Analytics
    "analytics.title": "Analytics",
    "analytics.subtitle": "In-depth analysis of public fund utilization",
    "analytics.categoryDist": "Category Distribution",
    "analytics.stateComparison": "State-wise Comparison",
    "analytics.districtComparison": "District-wise Comparison",
    "analytics.deptPerformance": "Department Performance",
    "analytics.department": "Department",
    "analytics.allocatedCr": "Allocated (₹ Cr)",
    "analytics.spentCr": "Spent (₹ Cr)",
    "analytics.status": "Status",
    "analytics.onTrack": "On Track",
    "analytics.moderate": "Moderate",
    "analytics.behind": "Behind",
    // Footer
    "footer.tagline": "An initiative for public fund transparency across India. © 2026",
    // Chatbot
    "chatbot.title": "India Fund Tracker AI",
    "chatbot.subtitle": "Multilingual • All States • Live Data",
    "chatbot.welcome": "🇮🇳 Namaste! I can help you explore government schemes and spending data across all Indian states. Ask in any language.",
    "chatbot.quickQuestions": "Quick questions:",
    "chatbot.placeholder": "Ask about any scheme or state...",
    // SchemeCard
    "card.centralGovt": "Central Govt",
    "card.budget": "Budget",
    "card.spent": "Spent",
    "card.viewDetails": "View Details",
  },
  ta: {
    "nav.home": "முகப்பு",
    "nav.dashboard": "டாஷ்போர்டு",
    "nav.schemes": "திட்டங்கள்",
    "nav.analytics": "பகுப்பாய்வு",
    "nav.reportIssue": "சிக்கல் புகார்",
    "landing.badge": "இந்தியாவின் பொது நிதி வெளிப்படைத்தன்மை தளம்",
    "landing.title1": "இந்தியா",
    "landing.title2": "நிதி & திட்ட",
    "landing.title3": "கண்காணிப்பான்",
    "landing.subtitle": "இந்தியா முழுவதும் அரசு நலத்திட்டங்கள் எவ்வாறு ஒதுக்கீடு, செலவிடப்படுகின்றன என்பதை நேரடியாக கண்காணிக்கவும்.",
    "landing.exploreDashboard": "டாஷ்போர்டை ஆராயுங்கள்",
    "landing.viewAllSchemes": "அனைத்து திட்டங்களையும் பார்க்கவும்",
    "landing.howItWorks": "வெளிப்படைத்தன்மை எப்படி செயல்படுகிறது",
    "landing.howItWorksDesc": "இந்தியா முழுவதும் பொது பொறுப்புணர்வை உறுதி செய்ய வடிவமைக்கப்பட்ட அம்சங்கள்.",
    "landing.activeSchemes": "செயலில் உள்ள திட்டங்கள்",
    "landing.govProgrammes": "இந்தியா முழுவதும் அரசு நலத்திட்டங்கள்",
    "landing.schemesIn": "திட்டங்கள்:",
    "landing.viewAll": "அனைத்தையும் காண்க",
    "feature.realTimeTracking": "நேரடி கண்காணிப்பு",
    "feature.realTimeTrackingDesc": "அனைத்து மாநிலங்களிலும் ஒவ்வொரு ரூபாயையும் நேரடியாக கண்காணிக்கவும்.",
    "feature.proofVerification": "ஆதார சரிபார்ப்பு",
    "feature.proofVerificationDesc": "ஒவ்வொரு செலவும் விலைப்பட்டியல், புகைப்படங்கள் மற்றும் புவி-இருப்பிட தரவால் ஆதரிக்கப்படுகிறது.",
    "feature.dataAnalytics": "தரவு பகுப்பாய்வு",
    "feature.dataAnalyticsDesc": "துறைகள் மற்றும் மாநிலங்கள் முழுவதும் செலவு முறைகளைக் காட்டும் ஊடாடும் விளக்கப்படங்கள்.",
    "feature.aiFraudDetection": "AI மோசடி கண்டறிதல்",
    "feature.aiFraudDetectionDesc": "இயந்திர கற்றல் அசாதாரண செலவு முறைகளை தானாகவே கொடியிடுகிறது.",
    "feature.panIndiaCoverage": "அகில இந்திய கவரேஜ்",
    "feature.panIndiaCoverageDesc": "அனைத்து 28 மாநிலங்கள், 8 யூடிகள் மற்றும் மத்திய அரசு திட்டங்களை கண்காணிக்கவும்.",
    "feature.transparencyScore": "வெளிப்படைத்தன்மை மதிப்பெண்",
    "feature.transparencyScoreDesc": "ஒவ்வொரு திட்டமும் பொது பொறுப்புணர்வு மதிப்பெண் பெறுகிறது.",
    "stat.totalBudget": "மொத்த நிதி",
    "stat.totalSpent": "மொத்த செலவு",
    "stat.utilized": "பயன்படுத்தப்பட்டது",
    "stat.activeSchemes": "செயலில் உள்ள திட்டங்கள்",
    "stat.statesCovered": "மாநிலங்கள்",
    "stat.statesUTs": "மாநிலங்கள் & யூடிகள்",
    "stat.avgUtilization": "சராசரி பயன்பாடு",
    "stat.totalSchemes": "மொத்த திட்டங்கள்",
    "stat.departments": "துறைகள்",
    "stat.districts": "மாவட்டங்கள்",
    "stat.verifiedExpenses": "சரிபார்க்கப்பட்ட செலவுகள்",
    "stat.flaggedItems": "கொடியிடப்பட்டவை",
    "stat.needsReview": "மதிப்பாய்வு தேவை",
    "stat.fromDatabase": "தரவுத்தளத்திலிருந்து",
    "dashboard.title": "குடிமக்கள் டாஷ்போர்டு",
    "dashboard.subtitle": "பொது நிதி பயன்பாட்டின் நேரடி கண்ணோட்டம்",
    "dashboard.stateAllocation": "மாநில வாரியான ஒதுக்கீடு",
    "dashboard.topDistricts": "ஒதுக்கீடு படி சிறந்த மாவட்டங்கள்",
    "dashboard.budgetVsSpent": "நிதி vs செலவு (₹ கோடி)",
    "dashboard.byCategory": "வகை படி",
    "dashboard.fundDistribution": "நிதி விநியோகம்",
    "dashboard.deptSpending": "துறை வாரியான செலவு",
    "dashboard.allActiveSchemes": "அனைத்து செயலில் உள்ள திட்டங்கள்",
    "schemes.allIndia": "அகில இந்திய அரசு திட்டங்கள்",
    "schemes.stateSchemes": "திட்டங்கள்",
    "schemes.browseDesc": "பொது நலத்திட்டங்களை உலாவி கண்காணிக்கவும்",
    "schemes.search": "திட்டங்கள், மாநிலங்கள், துறைகளை தேடுங்கள்...",
    "schemes.allTypes": "அனைத்து வகைகள்",
    "schemes.centralGovt": "மத்திய அரசு",
    "schemes.stateGovt": "மாநில அரசு",
    "schemes.loading": "திட்டங்கள் ஏற்றப்படுகின்றன...",
    "schemes.noResults": "உங்கள் தேடலுக்கு பொருந்தும் திட்டங்கள் இல்லை.",
    "detail.allSchemes": "அனைத்து திட்டங்கள்",
    "detail.notFound": "திட்டம் கிடைக்கவில்லை",
    "detail.backToSchemes": "திட்டங்களுக்கு திரும்பு",
    "detail.spent": "செலவு",
    "detail.budget": "நிதி",
    "detail.remaining": "மீதம்",
    "detail.districtAllocation": "மாவட்ட வாரியான ஒதுக்கீடு",
    "detail.recentExpenses": "சமீபத்திய செலவுகள்",
    "detail.noExpenses": "இதுவரை செலவுகள் பதிவு செய்யப்படவில்லை.",
    "detail.districtBreakdown": "மாவட்ட விவரம்",
    "detail.district": "மாவட்டம்",
    "detail.allocated": "ஒதுக்கீடு",
    "detail.utilization": "பயன்பாடு",
    "detail.progress": "முன்னேற்றம்",
    "analytics.title": "பகுப்பாய்வு",
    "analytics.subtitle": "பொது நிதி பயன்பாட்டின் ஆழமான பகுப்பாய்வு",
    "analytics.categoryDist": "வகை விநியோகம்",
    "analytics.stateComparison": "மாநில வாரியான ஒப்பீடு",
    "analytics.districtComparison": "மாவட்ட வாரியான ஒப்பீடு",
    "analytics.deptPerformance": "துறை செயல்திறன்",
    "analytics.department": "துறை",
    "analytics.allocatedCr": "ஒதுக்கீடு (₹ கோடி)",
    "analytics.spentCr": "செலவு (₹ கோடி)",
    "analytics.status": "நிலை",
    "analytics.onTrack": "சரியான பாதையில்",
    "analytics.moderate": "நடுத்தரம்",
    "analytics.behind": "பின்தங்கியுள்ளது",
    "footer.tagline": "இந்தியா முழுவதும் பொது நிதி வெளிப்படைத்தன்மைக்கான முயற்சி. © 2026",
    "chatbot.title": "இந்தியா நிதி கண்காணிப்பான் AI",
    "chatbot.subtitle": "பல மொழி • அனைத்து மாநிலங்கள் • நேரடி தரவு",
    "chatbot.welcome": "🇮🇳 வணக்கம்! இந்தியா முழுவதும் அரசு திட்டங்கள் மற்றும் செலவு தரவை ஆராய உங்களுக்கு உதவ முடியும். எந்த மொழியிலும் கேளுங்கள்.",
    "chatbot.quickQuestions": "விரைவு கேள்விகள்:",
    "chatbot.placeholder": "எந்த திட்டம் அல்லது மாநிலம் பற்றி கேளுங்கள்...",
    "card.centralGovt": "மத்திய அரசு",
    "card.budget": "நிதி",
    "card.spent": "செலவு",
    "card.viewDetails": "விவரங்களைக் காண்க",
  },
  hi: {
    "nav.home": "होम",
    "nav.dashboard": "डैशबोर्ड",
    "nav.schemes": "योजनाएं",
    "nav.analytics": "विश्लेषण",
    "nav.reportIssue": "समस्या दर्ज करें",
    "landing.badge": "भारत का सार्वजनिक कोष पारदर्शिता मंच",
    "landing.title1": "भारत",
    "landing.title2": "कोष & योजना",
    "landing.title3": "ट्रैकर",
    "landing.subtitle": "पूरे भारत में सरकारी कल्याण योजनाओं के आवंटन, खर्च और सत्यापन की वास्तविक समय की जानकारी।",
    "landing.exploreDashboard": "डैशबोर्ड देखें",
    "landing.viewAllSchemes": "सभी योजनाएं देखें",
    "landing.howItWorks": "पारदर्शिता कैसे काम करती है",
    "landing.howItWorksDesc": "पूरे भारत में सार्वजनिक जवाबदेही सुनिश्चित करने के लिए डिज़ाइन की गई सुविधाएं।",
    "landing.activeSchemes": "सक्रिय योजनाएं",
    "landing.govProgrammes": "पूरे भारत में सरकारी कल्याण कार्यक्रम",
    "landing.schemesIn": "में योजनाएं",
    "landing.viewAll": "सभी देखें",
    "feature.realTimeTracking": "रीयल-टाइम ट्रैकिंग",
    "feature.realTimeTrackingDesc": "सभी राज्यों में हर रुपये की आवंटन से खर्च तक निगरानी।",
    "feature.proofVerification": "प्रमाण सत्यापन",
    "feature.proofVerificationDesc": "हर खर्च बिल, फोटो और भू-स्थान डेटा द्वारा समर्थित।",
    "feature.dataAnalytics": "डेटा विश्लेषण",
    "feature.dataAnalyticsDesc": "विभागों और राज्यों में खर्च पैटर्न दिखाने वाले इंटरैक्टिव चार्ट।",
    "feature.aiFraudDetection": "AI धोखाधड़ी पहचान",
    "feature.aiFraudDetectionDesc": "मशीन लर्निंग असामान्य खर्च पैटर्न को स्वचालित रूप से चिह्नित करती है।",
    "feature.panIndiaCoverage": "अखिल भारतीय कवरेज",
    "feature.panIndiaCoverageDesc": "सभी 28 राज्यों, 8 केंद्र शासित प्रदेशों और केंद्र सरकार की योजनाओं की निगरानी।",
    "feature.transparencyScore": "पारदर्शिता स्कोर",
    "feature.transparencyScoreDesc": "हर परियोजना को सार्वजनिक जवाबदेही स्कोर मिलता है।",
    "stat.totalBudget": "कुल बजट",
    "stat.totalSpent": "कुल खर्च",
    "stat.utilized": "उपयोग किया गया",
    "stat.activeSchemes": "सक्रिय योजनाएं",
    "stat.statesCovered": "राज्य शामिल",
    "stat.statesUTs": "राज्य और केंद्र शासित",
    "stat.avgUtilization": "औसत उपयोग",
    "stat.totalSchemes": "कुल योजनाएं",
    "stat.departments": "विभाग",
    "stat.districts": "जिले",
    "stat.verifiedExpenses": "सत्यापित खर्च",
    "stat.flaggedItems": "चिह्नित आइटम",
    "stat.needsReview": "समीक्षा आवश्यक",
    "stat.fromDatabase": "डेटाबेस से",
    "dashboard.title": "नागरिक डैशबोर्ड",
    "dashboard.subtitle": "सार्वजनिक कोष उपयोग का वास्तविक समय अवलोकन",
    "dashboard.stateAllocation": "राज्य-वार आवंटन",
    "dashboard.topDistricts": "आवंटन के अनुसार शीर्ष जिले",
    "dashboard.budgetVsSpent": "बजट vs खर्च (₹ करोड़)",
    "dashboard.byCategory": "श्रेणी अनुसार",
    "dashboard.fundDistribution": "कोष वितरण",
    "dashboard.deptSpending": "विभाग-वार खर्च",
    "dashboard.allActiveSchemes": "सभी सक्रिय योजनाएं",
    "schemes.allIndia": "अखिल भारतीय सरकारी योजनाएं",
    "schemes.stateSchemes": "योजनाएं",
    "schemes.browseDesc": "सार्वजनिक कल्याण कार्यक्रमों को ब्राउज़ और ट्रैक करें",
    "schemes.search": "योजनाएं, राज्य, विभाग खोजें...",
    "schemes.allTypes": "सभी प्रकार",
    "schemes.centralGovt": "केंद्र सरकार",
    "schemes.stateGovt": "राज्य सरकार",
    "schemes.loading": "योजनाएं लोड हो रही हैं...",
    "schemes.noResults": "आपकी खोज से मेल खाने वाली कोई योजना नहीं मिली।",
    "detail.allSchemes": "सभी योजनाएं",
    "detail.notFound": "योजना नहीं मिली",
    "detail.backToSchemes": "योजनाओं पर वापस जाएं",
    "detail.spent": "खर्च",
    "detail.budget": "बजट",
    "detail.remaining": "शेष",
    "detail.districtAllocation": "जिला-वार आवंटन",
    "detail.recentExpenses": "हालिया खर्च",
    "detail.noExpenses": "अभी तक कोई खर्च दर्ज नहीं हुआ।",
    "detail.districtBreakdown": "जिला विवरण",
    "detail.district": "जिला",
    "detail.allocated": "आवंटित",
    "detail.utilization": "उपयोग",
    "detail.progress": "प्रगति",
    "analytics.title": "विश्लेषण",
    "analytics.subtitle": "सार्वजनिक कोष उपयोग का गहन विश्लेषण",
    "analytics.categoryDist": "श्रेणी वितरण",
    "analytics.stateComparison": "राज्य-वार तुलना",
    "analytics.districtComparison": "जिला-वार तुलना",
    "analytics.deptPerformance": "विभाग प्रदर्शन",
    "analytics.department": "विभाग",
    "analytics.allocatedCr": "आवंटित (₹ करोड़)",
    "analytics.spentCr": "खर्च (₹ करोड़)",
    "analytics.status": "स्थिति",
    "analytics.onTrack": "सही रास्ते पर",
    "analytics.moderate": "मध्यम",
    "analytics.behind": "पिछड़ रहा है",
    "footer.tagline": "पूरे भारत में सार्वजनिक कोष पारदर्शिता के लिए एक पहल। © 2026",
    "chatbot.title": "भारत कोष ट्रैकर AI",
    "chatbot.subtitle": "बहुभाषी • सभी राज्य • लाइव डेटा",
    "chatbot.welcome": "🇮🇳 नमस्ते! मैं पूरे भारत में सरकारी योजनाओं और खर्च डेटा का पता लगाने में आपकी मदद कर सकता हूं। किसी भी भाषा में पूछें।",
    "chatbot.quickQuestions": "त्वरित प्रश्न:",
    "chatbot.placeholder": "किसी भी योजना या राज्य के बारे में पूछें...",
    "card.centralGovt": "केंद्र सरकार",
    "card.budget": "बजट",
    "card.spent": "खर्च",
    "card.viewDetails": "विवरण देखें",
  },
  ml: {
    "nav.home": "ഹോം",
    "nav.dashboard": "ഡാഷ്ബോർഡ്",
    "nav.schemes": "പദ്ധതികൾ",
    "nav.analytics": "വിശകലനം",
    "nav.reportIssue": "പ്രശ്നം റിപ്പോർട്ട് ചെയ്യുക",
    "landing.badge": "ഇന്ത്യയുടെ പൊതു ഫണ്ട് സുതാര്യത പ്ലാറ്റ്ഫോം",
    "landing.title1": "ഇന്ത്യ",
    "landing.title2": "ഫണ്ട് & പദ്ധതി",
    "landing.title3": "ട്രാക്കർ",
    "landing.subtitle": "ഇന്ത്യ മുഴുവൻ സർക്കാർ ക്ഷേമ പദ്ധതികളുടെ അനുവദനം, ചെലവ്, പരിശോധന എന്നിവയുടെ തത്സമയ ദൃശ്യത.",
    "landing.exploreDashboard": "ഡാഷ്ബോർഡ് പര്യവേക്ഷിക്കുക",
    "landing.viewAllSchemes": "എല്ലാ പദ്ധതികളും കാണുക",
    "landing.howItWorks": "സുതാര്യത എങ്ങനെ പ്രവർത്തിക്കുന്നു",
    "landing.howItWorksDesc": "ഇന്ത്യ മുഴുവൻ പൊതു ഉത്തരവാദിത്തം ഉറപ്പാക്കാൻ രൂപകൽപ്പന ചെയ്ത സവിശേഷതകൾ.",
    "landing.activeSchemes": "സജീവ പദ്ധതികൾ",
    "landing.govProgrammes": "ഇന്ത്യ മുഴുവൻ സർക്കാർ ക്ഷേമ പരിപാടികൾ",
    "landing.schemesIn": "പദ്ധതികൾ:",
    "landing.viewAll": "എല്ലാം കാണുക",
    "stat.totalBudget": "മൊത്തം ബജറ്റ്",
    "stat.totalSpent": "മൊത്തം ചെലവ്",
    "stat.utilized": "ഉപയോഗിച്ചു",
    "stat.activeSchemes": "സജീവ പദ്ധതികൾ",
    "stat.statesCovered": "സംസ്ഥാനങ്ങൾ",
    "stat.statesUTs": "സംസ്ഥാനങ്ങൾ & കേന്ദ്രഭരണ",
    "dashboard.title": "പൗരൻ ഡാഷ്ബോർഡ്",
    "dashboard.subtitle": "പൊതു ഫണ്ട് ഉപയോഗത്തിന്റെ തത്സമയ അവലോകനം",
    "dashboard.stateAllocation": "സംസ്ഥാനം അനുസരിച്ചുള്ള അനുവദനം",
    "dashboard.topDistricts": "അനുവദനം അനുസരിച്ചുള്ള ജില്ലകൾ",
    "dashboard.byCategory": "വിഭാഗം അനുസരിച്ച്",
    "dashboard.deptSpending": "വകുപ്പ് അനുസരിച്ചുള്ള ചെലവ്",
    "dashboard.allActiveSchemes": "എല്ലാ സജീവ പദ്ധതികളും",
    "schemes.allIndia": "അഖിലേന്ത്യ സർക്കാർ പദ്ധതികൾ",
    "schemes.search": "പദ്ധതികൾ, സംസ്ഥാനങ്ങൾ തിരയുക...",
    "schemes.loading": "പദ്ധതികൾ ലോഡ് ചെയ്യുന്നു...",
    "footer.tagline": "ഇന്ത്യ മുഴുവൻ പൊതു ഫണ്ട് സുതാര്യതയ്ക്കുള്ള ഒരു സംരംഭം. © 2026",
    "chatbot.welcome": "🇮🇳 നമസ്കാരം! ഇന്ത്യ മുഴുവൻ സർക്കാർ പദ്ധതികളും ചെലവ് ഡാറ്റയും പര്യവേക്ഷിക്കാൻ എനിക്ക് സഹായിക്കാം.",
    "card.viewDetails": "വിശദാംശങ്ങൾ കാണുക",
  },
  te: {
    "nav.home": "హోమ్",
    "nav.dashboard": "డ్యాష్‌బోర్డ్",
    "nav.schemes": "పథకాలు",
    "nav.analytics": "విశ్లేషణ",
    "nav.reportIssue": "సమస్యను నివేదించండి",
    "landing.badge": "భారతదేశ ప్రజా నిధి పారదర్శకత వేదిక",
    "landing.title1": "భారతదేశ",
    "landing.title2": "నిధి & పథక",
    "landing.title3": "ట్రాకర్",
    "landing.subtitle": "భారతదేశం అంతటా ప్రభుత్వ సంక్షేమ పథకాల కేటాయింపు, ఖర్చు మరియు ధృవీకరణపై నిజ-సమయ సమాచారం.",
    "landing.exploreDashboard": "డ్యాష్‌బోర్డ్ అన్వేషించండి",
    "landing.viewAllSchemes": "అన్ని పథకాలు చూడండి",
    "stat.totalBudget": "మొత్తం బడ్జెట్",
    "stat.totalSpent": "మొత్తం ఖర్చు",
    "stat.utilized": "వినియోగించబడింది",
    "stat.activeSchemes": "సక్రియ పథకాలు",
    "dashboard.title": "పౌర డ్యాష్‌బోర్డ్",
    "schemes.allIndia": "అఖిల భారత ప్రభుత్వ పథకాలు",
    "schemes.search": "పథకాలు, రాష్ట్రాలు వెతకండి...",
    "footer.tagline": "భారతదేశం అంతటా ప్రజా నిధి పారదర్శకత కోసం ఒక చొరవ. © 2026",
    "chatbot.welcome": "🇮🇳 నమస్కారం! భారతదేశం అంతటా ప్రభుత్వ పథకాలు మరియు ఖర్చు డేటాను అన్వేషించడంలో నేను సహాయం చేయగలను.",
    "card.viewDetails": "వివరాలు చూడండి",
  },
  kn: {
    "nav.home": "ಮುಖಪುಟ",
    "nav.dashboard": "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
    "nav.schemes": "ಯೋಜನೆಗಳು",
    "nav.analytics": "ವಿಶ್ಲೇಷಣೆ",
    "nav.reportIssue": "ಸಮಸ್ಯೆ ವರದಿ ಮಾಡಿ",
    "landing.badge": "ಭಾರತದ ಸಾರ್ವಜನಿಕ ನಿಧಿ ಪಾರದರ್ಶಕತಾ ವೇದಿಕೆ",
    "landing.title1": "ಭಾರತ",
    "landing.title2": "ನಿಧಿ & ಯೋಜನೆ",
    "landing.title3": "ಟ್ರ್ಯಾಕರ್",
    "landing.subtitle": "ಭಾರತಾದ್ಯಂತ ಸರ್ಕಾರಿ ಕಲ್ಯಾಣ ಯೋಜನೆಗಳ ಹಂಚಿಕೆ, ಖರ್ಚು ಮತ್ತು ಪರಿಶೀಲನೆಯ ನೈಜ-ಸಮಯ ಮಾಹಿತಿ.",
    "landing.exploreDashboard": "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್ ಅನ್ವೇಷಿಸಿ",
    "landing.viewAllSchemes": "ಎಲ್ಲಾ ಯೋಜನೆಗಳನ್ನು ನೋಡಿ",
    "stat.totalBudget": "ಒಟ್ಟು ಬಜೆಟ್",
    "stat.totalSpent": "ಒಟ್ಟು ಖರ್ಚು",
    "stat.utilized": "ಬಳಸಲಾಗಿದೆ",
    "stat.activeSchemes": "ಸಕ್ರಿಯ ಯೋಜನೆಗಳು",
    "dashboard.title": "ನಾಗರಿಕ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
    "schemes.allIndia": "ಅಖಿಲ ಭಾರತ ಸರ್ಕಾರಿ ಯೋಜನೆಗಳು",
    "schemes.search": "ಯೋಜನೆಗಳು, ರಾಜ್ಯಗಳನ್ನು ಹುಡುಕಿ...",
    "footer.tagline": "ಭಾರತಾದ್ಯಂತ ಸಾರ್ವಜನಿಕ ನಿಧಿ ಪಾರದರ್ಶಕತೆಗಾಗಿ ಒಂದು ಉಪಕ್ರಮ. © 2026",
    "chatbot.welcome": "🇮🇳 ನಮಸ್ಕಾರ! ಭಾರತಾದ್ಯಂತ ಸರ್ಕಾರಿ ಯೋಜನೆಗಳು ಮತ್ತು ಖರ್ಚು ಡೇಟಾವನ್ನು ಅನ್ವೇಷಿಸಲು ನಾನು ಸಹಾಯ ಮಾಡಬಲ್ಲೆ.",
    "card.viewDetails": "ವಿವರಗಳನ್ನು ನೋಡಿ",
  },
  mr: {
    "nav.home": "मुखपृष्ठ",
    "nav.dashboard": "डॅशबोर्ड",
    "nav.schemes": "योजना",
    "nav.analytics": "विश्लेषण",
    "nav.reportIssue": "समस्या नोंदवा",
    "landing.badge": "भारताचे सार्वजनिक निधी पारदर्शकता व्यासपीठ",
    "landing.title1": "भारत",
    "landing.title2": "निधी & योजना",
    "landing.title3": "ट्रॅकर",
    "landing.subtitle": "संपूर्ण भारतातील सरकारी कल्याण योजनांच्या वाटप, खर्च आणि पडताळणीची रिअल-टाइम माहिती.",
    "landing.exploreDashboard": "डॅशबोर्ड पहा",
    "landing.viewAllSchemes": "सर्व योजना पहा",
    "stat.totalBudget": "एकूण अर्थसंकल्प",
    "stat.totalSpent": "एकूण खर्च",
    "stat.utilized": "वापर केला",
    "stat.activeSchemes": "सक्रिय योजना",
    "dashboard.title": "नागरिक डॅशबोर्ड",
    "schemes.allIndia": "अखिल भारतीय सरकारी योजना",
    "schemes.search": "योजना, राज्ये शोधा...",
    "footer.tagline": "संपूर्ण भारतातील सार्वजनिक निधी पारदर्शकतेसाठी एक उपक्रम. © 2026",
    "chatbot.welcome": "🇮🇳 नमस्कार! संपूर्ण भारतातील सरकारी योजना आणि खर्च डेटा शोधण्यात मी मदत करू शकतो.",
    "card.viewDetails": "तपशील पहा",
  },
  bn: {
    "nav.home": "হোম",
    "nav.dashboard": "ড্যাশবোর্ড",
    "nav.schemes": "প্রকল্প",
    "nav.analytics": "বিশ্লেষণ",
    "nav.reportIssue": "সমস্যা জানান",
    "landing.badge": "ভারতের জনতা তহবিল স্বচ্ছতা প্ল্যাটফর্ম",
    "landing.title1": "ভারত",
    "landing.title2": "তহবিল & প্রকল্প",
    "landing.title3": "ট্র্যাকার",
    "landing.subtitle": "সমগ্র ভারত জুড়ে সরকারি কল্যাণ প্রকল্পের বরাদ্দ, ব্যয় এবং যাচাইয়ের রিয়েল-টাইম তথ্য।",
    "landing.exploreDashboard": "ড্যাশবোর্ড দেখুন",
    "landing.viewAllSchemes": "সব প্রকল্প দেখুন",
    "stat.totalBudget": "মোট বাজেট",
    "stat.totalSpent": "মোট ব্যয়",
    "stat.utilized": "ব্যবহৃত",
    "stat.activeSchemes": "সক্রিয় প্রকল্প",
    "dashboard.title": "নাগরিক ড্যাশবোর্ড",
    "schemes.allIndia": "সর্বভারতীয় সরকারি প্রকল্প",
    "schemes.search": "প্রকল্প, রাজ্য খুঁজুন...",
    "footer.tagline": "সমগ্র ভারত জুড়ে জনতা তহবিল স্বচ্ছতার জন্য একটি উদ্যোগ। © 2026",
    "chatbot.welcome": "🇮🇳 নমস্কার! সমগ্র ভারত জুড়ে সরকারি প্রকল্প এবং ব্যয়ের তথ্য অনুসন্ধানে আমি সাহায্য করতে পারি।",
    "card.viewDetails": "বিস্তারিত দেখুন",
  },
};

type LanguageContextType = {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
};

const LanguageContext = createContext<LanguageContextType>({
  language: "en",
  setLanguage: () => {},
  t: (key: string) => key,
});

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem("pft-language");
    return (saved as Language) || "en";
  });

  const setLanguage = useCallback((lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("pft-language", lang);
  }, []);

  const t = useCallback((key: string): string => {
    return translations[language]?.[key] || translations.en[key] || key;
  }, [language]);

  useEffect(() => {
    document.documentElement.lang = language;
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
